name: simpannow
description: Personal Finance Flutter Web App

# Specify Flutter SDK version constraints
environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: 2.24.0
  firebase_auth: 4.15.0
  cloud_firestore: 4.13.3
  firebase_analytics: 10.7.2
  # Add explicit web dependencies
  firebase_core_web: 2.10.0
  firebase_auth_web: 5.8.9
  cloud_firestore_web: 3.8.7
  # Add JS interop dependency that provides missing types
  js: ^0.6.7
  
  provider: ^6.0.5
  flutter_spinkit: ^5.2.0
  fluttertoast: ^8.2.2
  font_awesome_flutter: ^10.5.0
  shared_preferences: ^2.2.2
  
  # The following adds the Cupertino Icons font to your application
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
